name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          mkdir docs
          mv public/* docs
          echo "Your Hugo website has been built and deployed!"
        env:
          HUGO_VERSION: 'latest'

      - name: Commit and Push changes
        run: |
          git config --global user.email "<mantaplattenvernichter@gmail.com>"
          git config --global user.name "meatpiet"
          git add .
          git commit -m "Deploy website"
          git push origin main
